### ISSUE TITLE
program won't accept any integer as word count

### ISSUE THREAD

**Issue by otmezger** [ioguntol/Hangman-Solver#1]
Hi, 
I just downloaded the code and ran it in Xcode. It compiles and asks me for a word length. It doesn't matter what I enter there, it always says "Sorry, I must not have your word in my dictionary."

what am I doing wrong? Thanks
<img width="959" alt="screen shot 2016-08-15 at 11 20 36" src="https://cloud.githubusercontent.com/assets/2758346/17672636/8e727816-62da-11e6-8229-27ea808e6b90.png">

**Comment by ini** [comment]
To get it working, either change your working directory to '$PROJECT_DIR/Hangman Solver' in your build scheme's settings (Product > Scheme > Edit Scheme), or run main.cpp from the command line instead of from Xcode.

**Comment by ini** [comment]
I've now updated the default scheme so you don't have to manually set it.
